---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
  namespace: hello-chris
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
secrets:
- name: git-ssh
