apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-chris
    app.kubernetes.io/component: hello-chris
    app.kubernetes.io/instance: hello-chris
  name: hello-chris
  namespace: hello-chris
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: hello-chris
  strategy: {}
  template:
    metadata:
      labels:
        deployment: hello-chris
    spec:
      containers:
      - image: 'quay.io/cnuland/hello-chris:latest'
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}